### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by mehti1367** [NabiKAZ/filimo-downloader#10]
سلام ، اسکریپتی که نوشتین فقط اعضای که اشتراک خریدن رو لوگین میکنه ؟ چون من الان کاربر عادی هستم ولی با اینکه پسوردم رو درست میزنم وارد سیستم نمیشه و از دوباره ازم نام کاربری و پسورد رو میخواد ، اینو بخاطر این گفتم که چون فیلیمو واسه ماه رمضان اجازه داده همه کاربرها روزی 1 دونه فیلم رو تماشا کنند...

**Comment by NabiKAZ** [comment]
<div dir=rtl>

برای هر کاربری باید لاگین بشه، من الان تست کردم مشکلی ندیدم.
شاید از نسخه قدیمی استفاده میکنید، [آخرین نسخه](https://github.com/NabiKAZ/filimo-downloader/archive/master.zip) رو اکنون دانلود و دوباره تست کنید و از پسورد ثابتتون استفاده کنید و نه پسورد موقتی که براتون پیامک میشه.

**Comment by mehti1367** [comment]
من متوجه یه نکته ای شدم جدیدا فیلیمو نسبت به آی اس بی کاربر دامین رو عوض میکنه ، الان اینترنت من های وب هستش دامین شده vod.hiweb.ir

برای دوستم که اسیاتک شده vod.asiatech.ir 

این مورد تاثیر نداره ؟ چون اخرین نسخه رو دانلود کردم باز نشد

**Comment by mehti1367** [comment]
اره مشکل همینه من الان ادرس رو عوض کردم داخل فایل پی اچ پی اکی شد

**Comment by NabiKAZ** [comment]
<div dir=rtl>

البته این تغییر آدرس برای من هم هست و با تستی که من کردم در این خصوص مشکلی مشاهده نکردم.
در هر صورت خوشحالم که مشکل شما حل شد.
یک مشکل دیگه هم در خصوص گرفتن کاور فیلم همین الان حل شد که میتونید آپدیت کنید.
