### ISSUE TITLE
Better download speed

### ISSUE THREAD

**Issue by runo280** [NabiKAZ/filimo-downloader#11]
من [این خط](https://github.com/NabiKAZ/filimo-downloader/blob/f19e4f41ef54521c0c322d4f089647f9fcb868d9/download.php#L109) رو این شکلی کردم سرعت دانلود خیلی بهتر شد برام:
`$cmd = 'youtube-dl --cookies config/cookies.txt --external-downloader aria2c -i "' . $qualities[$input]['url'] . '" -o "' . $video_file . '"';`

کارتون هم حرف نداره 👍

**Comment by NabiKAZ** [comment]
<div dir=rtl>
از نقطه نظری که ارائه دادید ممنونم.  

حرف شما درست بود؛ اما youtube-dl هم از همون ffmpeg که ما استفاده میکنیم، استفاده کرده بود. به همین خاطر کمی اون رو بررسی کردم و متوجه شدم یا تغییر پارامترهای ffmpeg میشه به اون سرعت رسید.  

توضیح فنیش هم اینه که وقتی فورمت خروجی رو تعریف نکنیم، ffmpeg از فورمتهای پیشفرضی استفاده میکنه که برای اونها باید کانورت صورت بگیره و این تاخیر زمانی نسبی رو همراه خواهد داشت. اما وقتی پارامتر ‎`-c:v copy -c:a copy` رو استفاده میکنیم. از همون فورمت های صوتی و تصویری سورس استفاده میکنه و بنابراین دیگه کانورتی صورت نمیگیره و خب هم از نظر سرعت دانلود سریعتر خواهد بود و هم cpu رو اصلاً درگیر نمیکنه.  

در نهایت تغییراتی در کد دادم که الان در نسخه فعلی، سرعت برنامه تا حدود 2 برابر بیشتر شده است.  

تشکر
