### ISSUE TITLE
پیام خطای نامشخص بعد از ورود آی‌دی ویدئو

### ISSUE THREAD

**Issue by ehsan957** [NabiKAZ/filimo-downloader#13]
![untitled](https://user-images.githubusercontent.com/1728920/41590425-317dd43e-73cc-11e8-9b2d-3772b7fbce0d.png)

روی ویندوز PHP 7.2 نصب هست فایل اجرایی FFmpeg را هم به این فولدر منتقل کردم ولی موقع دانلود بعد از ورود آی دی با چنین ارروی مواجه میشم

**Comment by NabiKAZ** [comment]
<div dir=rtl>

متاسفانه توی ویندوز پیامهای خطا فارسی رو درست نشون نمیده.
شما خط 25 یعنی درست جایی که داره پیام خطا رو نشون میده، این خط رو اضافه کنید:
</div>

```PHP
file_put_contents('error.txt', $contents);
```
<div dir=rtl>

بعد محتوای فایل `error.txt` رو بزارید ببینیم پیام خطا چی هست.
ممکنه خطایی مربوط به دسترسی شما به فیلیمو باشه.

پ.ن: در گیتهاب، با این `<div dir=rtl>` میتونید نوشته ها رو راست چین کنید 😉 
</div>

**Comment by ehsan957** [comment]
با اوبونتو تست کردم پیام داد

کاربر یافت نشد.

ولی من با فایرفاکس توی فیلیمو لاگین هم کرده بودم

**Comment by NabiKAZ** [comment]
<div dir=rtl>

اگر پیغام میده `کاربر یافت نشد.` قطعاً همینطوره، چراکه این پیام از سمت فیلیمو برگشت داده شده.
دقت کنید که نام کاربری که شما وارد میکنید `l5fLa` هست و مطمئن بشید که نام کاربریتون رو درست وارد میکنید.

**Comment by ehsan957** [comment]
اشتباه از من بود در ورود نام کاربری

ببخشید که با بی‌دقتی این ایراد را گرفتم

**Comment by NabiKAZ** [comment]
<div dir=rtl>

@ehsan957 نه خواهش میکنم. خوشحالم که مشکل شما حل شد. :-)
