### ISSUE TITLE
مشکل در لاگین

### ISSUE THREAD

**Issue by ghost** [NabiKAZ/filimo-downloader#15]
<div dir=rtl>

سلام
من از اینتزنت آسیاتک استفاده می کنم و یوزر رایگان دارم 
پس از وارد کردن یوزر و پسورد لاگین میشه ولی دوباره یوزر و پسورد رو می پرسه
پ.ن:پس از وارد کردن یوزر و تایید آن رمز ورود از طرف فیلیمو ارسال می شه 
البته بازدن همون رمز هم همین مشکل رو داره.

باتشکر

**Comment by NabiKAZ** [comment]
<div dir=rtl>

1. من فقط با پسورد ثابت تست کردم. شما هم همینطور تست کنید و نتیجه رو بفرمائید. (از پسورد یک بار مصرفی که براتون پیامک میشه استفاده نکنید.)
2. یه تست دیگه هم انجام بدید. با فیلترشکن که IP غیر ایرانی باشه روی بروزر تست کنید که دقیقاً از دامنه اصلی فیلیمو (https://www.filimo.com) بدون مشکل امکان لاگین دارید؟ (چون در وضعیت عادی احتمالاً دامنه ریدایرکت میشه به ساب دامین isp)
3. همچنین مطمئن بشید که از [آخرین نسخه](https://github.com/NabiKAZ/filimo-downloader/archive/master.zip) استفاده میکنید.
4. لطفاً سیستم عاملتون هم بفرمائید.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

به دلیل گذشت زمان زیاد و عدم پاسخ، فرض بر حل موضوع گذاشته میشود و تیکت بسته میشود.
چنانچه مشکل شما هنوز حل نشده، میتوانید زیر همین موضوع دوباره دنبال کنید.
