### ISSUE TITLE
مشکل تابع curl_init

### ISSUE THREAD

**Issue by najafi2725** [NabiKAZ/filimo-downloader#16]
Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\Helena\Desktop\filimo-downloader-master\download.php:157
Stack trace:
#0 C:\Users\Helena\Desktop\filimo-downloader-master\download.php(14): get_contents('https://www.fil...')
#1 {main}
  thrown in C:\Users\Helena\Desktop\filimo-downloader-master\download.php on line 157
چ کنم؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

شما باید ماژول CURL رو روی PHP خودتون فعال کنید.

فایل php.ini رو ویرایش کنید و این خط رو پیدا کنید: extension=php_curl.dll و اولش ";" رو حذف کنید.

**Comment by aaalli** [comment]
بنده اینکار را اعمال کردم داخل

php.ini

بعد از دستور اصلا نوشته خاصی کلا ظاهر نمیشه!!

http://uupload.ir/files/i7km_untitl4554ed.png

اینم اسکرین راه حلی هست؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

@aaalli 
شرایط شما متفاوته دوست من، چون پیروی تیکت #21 من از شما خواسته بودم یک die وسط کد بگذارید که اون ممکنه موجب توقف عملیات شده بنابراین میتونه موضوع به curl مربوط نباشه، بنابراین در همون تیکت لطفاً پیگیری کنید تا مشکل شما حل بشه.
