### ISSUE TITLE
مشکل curl

### ISSUE THREAD

**Issue by najafi2725** [NabiKAZ/filimo-downloader#17]
من تو فایل php خودم چیزی که گفتید ندارم 
باید سرور داشته باشم یا رو ویندوز خودمم میشه؟

**Comment by najafi2725** [comment]
XAMPP باید داشته باشم؟

**Comment by najafi2725** [comment]
حل شد مرسی

**Comment by NabiKAZ** [comment]
<div dir=rtl>

خوشحالم که مشکلتون حل شد. فقط زیر همون موضوع [قبلی ](https://github.com/NabiKAZ/filimo-downloader/issues/16)میتونستید ریپلای بزنید :-)
