### ISSUE TITLE
خرابی فیلیمو دانلودر

### ISSUE THREAD

**Issue by aaalli** [NabiKAZ/filimo-downloader#19]
سلام و خسته نباشید خدمت شما دوست عزیز
ببخشید بنده از این سورس استفاده کردم و دو فیلم دانلود کردم از دیروز بعد از ظهر دیگه کیفیت هارا نشون نمیده که دانلود کنید!!

غیرفعال شده یا مشکل برای سورس پیش اومده؟

در قسمت انتخاب گزینه کیفیت اصلا گزینه ای نمیاره

**Comment by NabiKAZ** [comment]
<div dir=rtl>

سلام و تشکر،

خوشحالم که برنامه برای شما مفید واقع شده.

ظاهراً فیلیمو تغییر اساسی در پلیر خود داده و اطلاعات پیلیر به شکل `JSON` دراومده.

در هر صورت تغییرات مورد نیاز جهت تطبیق، داده شد و اکنون برنامه به خوبی کار میکند.

لطفاً دوباره تست کنید و اگر بازهم به مشکلی برخورد کردید اطلاع دهید.
