### ISSUE TITLE
ایراد در دانلود از امروز

### ISSUE THREAD

**Issue by Kaveh619** [NabiKAZ/filimo-downloader#20]
سلام خسته نباشی...از امروز که من چک کردم توی دانلود مشکل داره...

فایل جدید هم جایگزین کردم و کوکی ها رو پاک کردم...

ولی این ارور رو میده : 
Error: Can not fetch video URL.

Warning: array_multisort(): Argument #1 is expected to be an array or a sort flag in C:\wamp64\www\filimo\download.php on line 192

Warning: array_combine(): Both parameters should have an equal number of elements in C:\wamp64\www\filimo\download.php on line 98
Select Quality:

Warning: Invalid argument supplied for foreach() in C:\wamp64\www\filimo\download.php on line 101
Input option number:

**Comment by NabiKAZ** [comment]
<div dir=rtl>

فکر میکنم مشکلتون در راستای همون مشکل تیکت #19 بوده باشه که من دیروز روش کار کردم و حل شد.
الان برای من خطایی ظاهر نمیشه.
ضمناً مطمئن بشید که آخرین نسخه رو تازه دانلود کردید.
اگر که بازهم احساس کردید که مشکلی بوجود داره، لطفاً اطلاع بدید.
