### ISSUE TITLE
ارور بعضی از آدرس ها

### ISSUE THREAD

**Issue by aaalli** [NabiKAZ/filimo-downloader#21]
سلام داداش خوبی
یکی دوتا از فیلما این ارورا میده : 
Error: Can not fetch video URL.

علتش چیه؟

این ارور روی همه فیلما نیست.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

سلام و ممنون از احوال پرسی های شما.

لطفاً یک نمونه از فیلم‌هایی که این مشکل رو داره رو بفرمائید تا بشه دقیقتر مسئله رو بررسی کرد.

**Comment by aaalli** [comment]
به خدمت شما عرض شود برای مثال فیلم لاتاری که جدیدا داخل فیلمیو بارگزاری شده این ارور را میده!

**Comment by aaalli** [comment]
آیدی ویدیو : 

24S7Y

**Comment by NabiKAZ** [comment]
<div dir=rtl>

من تست کردم مشکلی ندیدم. 
آیا شما مطمئن هستید که آخرین نسخه رو که دو روز پیش تغییراتی داشته، دانلود کردید؟
و سیستم عاملتون چیه؟

**Comment by aaalli** [comment]
...ممنون از شما من دیشب تست کردم و این مشکل بود و در تستی که الان داشتم همچین اروری نداد

تشکر

**Comment by aaalli** [comment]
همه فیلم ها ارور نمیده

بعضی هاش اینجوریه و سیستم عامل بنده ویندوز 7

**Comment by NabiKAZ** [comment]
<div dir=rtl>

فایل download.php رو باز کنید، بعد از خط 73 (preg_match) این خط رو اضافه کنید:
</div>

```
var_dump($match);die;
```
<div dir=rtl>

سپس دوباره امتحان کنید و خروجی رو اینجا بزارید.

**Comment by aaalli** [comment]
این ارور بیشتر شد
از زدن دستور دانلود تا ارور

**C:\Users\ALI\Downloads\filimo1>php download.php
Filimo Downloader - version 0.1.0 - Copyright 2017
By Nabi KaramAliZadeh <www.nabi.ir> <nabikaz@gmail.com>
Signup here: http://filimo.com/invite/NabiKAZ/a8ca
Project link: https://github.com/NabiKAZ/filimo-downloader
===========================================================

Fatal error: Uncaught Error: Call to undefined function curl_init()
ALI\Downloads\filimo1\download.php:162
Stack trace:
#0 C:\Users\ALI\Downloads\filimo1\download.php(14): get_contents('ht
l...')
#1 {main}
  thrown in C:\Users\ALI\Downloads\filimo1\download.php on line 162**

**Comment by aaalli** [comment]
این ارور بیشتر شد
از زدن دستور دانلود تا ارور

**C:\Users\ALI\Downloads\filimo1>php download.php
Filimo Downloader - version 0.1.0 - Copyright 2017
By Nabi KaramAliZadeh <www.nabi.ir> nabikaz@gmail.com
Signup here: http://filimo.com/invite/NabiKAZ/a8ca
Project link: https://github.com/NabiKAZ/filimo-downloader
**Fatal error: Uncaught Error: Call to undefined function curl_init()
ALI\Downloads\filimo1\download.php:162
Stack trace:
#0 C:\Users\ALI\Downloads\filimo1\download.php(14): get_contents('ht
l...')
#1 {main}
thrown in C:\Users\ALI\Downloads\filimo1\download.php on line 162****

**Comment by NabiKAZ** [comment]
<div dir=rtl>

این خطای اخیر مربوط به CURL است که در تیکت #16 راه حل رو نوشتم.

**Comment by aaalli** [comment]
بنده اینکار را اعمال کردم داخل

php.ini

بعد از دستور اصلا نوشته خاصی کلا ظاهر نمیشه!!

http://uupload.ir/files/i7km_untitl4554ed.png

اینم اسکرین راه حلی هست؟

**Comment by aaalli** [comment]
بنظرم فایل
php.ini
فقط در سرور ویندوزی قابل یافته!!

و در ویندوز سیستم معمولی نیست!

یک نرم افزار مکمل داره؟

**Comment by NabiKAZ** [comment]
> بعد از دستور اصلا نوشته خاصی کلا ظاهر نمیشه!!
<div dir=rtl>

ابتدای فایل download.php و بعد از خط `<?php` این دستور رو اضافه کنید و دوباره تست کنید:
</div>

```
error_reporting(E_ALL);
```

<div dir=rtl>
ضمناً خروجی این دستور را هم بگذارید:
</div>

```
php -v
```

> بنظرم فایل
> php.ini
> فقط در سرور ویندوزی قابل یافته!!
> و در ویندوز سیستم معمولی نیست!
> یک نرم افزار مکمل داره؟

<div dir=rtl>

فرقی نمیکنه، این فایل تنظیمات PHP هست و اگرم وجود نداشت خودتون میتونید اون رو بسازید.
نرم افزار اضافه خاصی هم نیاز نیست.
اگر میخواستید بدونید مسیر فایل php.ini که PHP شما در حال حاضر داره استفاده میکنه کجاست، این دستور مفیده:
</div>

```
php --ini
```

<div dir=rtl>

شما اگر مطمئن نیستید که CURL نصب هست میتونید خروجی این دستور رو چک کنید:

</div>

```
php -i | grep curl
```
<div dir=rtl>

_(در power shell)_
</div>

**Comment by aaalli** [comment]
خروجی دستور php -v

PHP 7.1.10 (cli) (built: Sep 26 2017 20:03:48) ( NTS MSVC14 (
4 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by aaalli** [comment]
این کار هایی که گفتید انجام دادم

http://uupload.ir/files/i7km_untitl4554ed.png

باز هم همین جا متوقف میشه

میتونید متن مورد نظر 
`php.ini`
اینجا بگذارید؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

مطمئن هستید error_reporting(E_ALL);  رو اضافه کردید ولی خطایی ظاهر نمیشه؟!!!
لطفاً روی تلگرام @nabikaz با من در ارتباط باشید، شاید نیاز باشه بیام روی سیستمتون چک کنم.

**Comment by NabiKAZ** [comment]
فکر میکنم با آخرین تغییرات و صحبتهایی که داشتیم این مشکل حل شده باشه.
اگر بازهم مشکلی بود تیکت رو میتونید باز کنید.
