### ISSUE TITLE
error 161

### ISSUE THREAD

**Issue by sisimas** [NabiKAZ/filimo-downloader#22]
سلام من همه مراحل

ل رو انجام دادم ولی وقتی php dowmload.php رو اجرا کردم این اروو رو داد. 
![fghfgbh](https://user-images.githubusercontent.com/42911952/44956788-a0e2f000-aede-11e8-90c0-3dbdffbf6d98.JPG)

**Comment by NabiKAZ** [comment]
<div dir=rtl>

دوست من، این خطا مربوط به CURL است که باید فعال شود. در تیکت #16 راه حل رو نوشتم.

**Comment by sisimas** [comment]
ممنون

من روی هر دو تا فایلی که داشتم این مورد رو اجرا کردم. طبق عکس

![gfbf](https://user-images.githubusercontent.com/42911952/44985044-2aa0c500-af94-11e8-879e-ac764239a5b8.JPG)

اما بازم همون اررور رو داد . بازم طبق عکس

![ghfg](https://user-images.githubusercontent.com/42911952/44985042-2a082e80-af94-11e8-8592-55b731e0e2b8.JPG)

**Comment by sisimas** [comment]
چی شد دوست عزیز پاسخ من؟؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

پوزش بابت تاخیر،
فایل php.ini-production رو به php.ini تغییر نام دهید.
