### ISSUE TITLE
مشکل انتخاب کیفیت دانلود در برخی 

### ISSUE THREAD

**Issue by alipour66m** [NabiKAZ/filimo-downloader#23]
سلام
بعضی از فیلم ها در انتخاب کیفیت دانلود ارور زیر می دهد
مثلا این فیلم : YpAeb
Error: Can not fetch video URL.
PHP Warning:  array_multisort(): Argument #1 is expected to be an array or a sort flag in C:\xampp\htdocs\1\download.php on line 192

Warning: array_multisort(): Argument #1 is expected to be an array or a sort flag in C:\xampp\htdocs\1\download.php on line 192
PHP Warning:  array_combine(): Both parameters should have an equal number of elements in C:\xampp\htdocs\1\download.php on line 98

Warning: array_combine(): Both parameters should have an equal number of elements in C:\xampp\htdocs\1\download.php on line 98
Select Quality:
PHP Warning:  Invalid argument supplied for foreach() in C:\xampp\htdocs\1\download.php on line 101

Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\1\download.php on line 101

**Comment by NabiKAZ** [comment]
<div dir=rtl>

باتشکر از شما بابت گزارش مشکل.

مشکل حل شد.

لطفاً دوستان روی ویدیوهای مختلف تست کنند و چنانچه مشکلی بود اطلاع دهند.
