### ISSUE TITLE
Conversion failed!

### ISSUE THREAD

**Issue by amircyber** [NabiKAZ/filimo-downloader#24]
Malformed AAC bitstream detected
to fix :
Modify line 102 to:
$cmd = 'ffmpeg ' . $cmd_proxy . ' -i "' . $qualities[$input]['url'] . '" -c:v copy **-bsf:a aac_adtstoasc** -c:a copy -y "' . $video_file . '"';

**Comment by NabiKAZ** [comment]
<div dir="rtl">
آیا این پیشنهاد خودتون بوده یا از سمت نرم افزاری این خطا رو دریافت کردید؟ لطفاً اطلاعات بیشتری در ارتباط با مسئله ارائه کنید.

**Comment by NabiKAZ** [comment]
با توجه به گذشت بیش از 1 ماه از موضوع و عدم دریافت پاسخ، مسئله حل شده فرض شده و بسته میشود.
لطفاً چنانچه مشکل باقی بود، آن را باز کنید.
