### ISSUE TITLE
loop login

### ISSUE THREAD

**Issue by ubzippo** [NabiKAZ/filimo-downloader#26]
باسلام
جدیدا فیلیمو تغییراتی در سایتش داده که باعث میشه در داس هرچقدر مشخصات لاگین رو وارد میکنی بازم ازت مشخصات رو بخواد. در حالیکه خود برنامه میگه مشخصاتتون درسته و وارد شدید
لطفا فیکسش کنید خیلی ممنون میشم

سپاسگذار.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

ممنون از گزارش اشکال.

اینطور به نظر میرسه که آپارات تغییرات اساسی در سیستم احراز هویت و لاگین انجام داده که با تغییرات کوچکی نمیشه اون رو حل کرد و نیاز به صرف زمان بیشتری برای بازنویسی این بخش هست.
در اولین فرصت روی این موضوع کار خواهم کرد.

**Comment by ubzippo** [comment]
خیلی ممنون
لطفا یه وقتی رو ازاد کنین روش کار کنین. این برنامه شما خیلی به من کمک میکرد و کار منو راحت

**Comment by alipour66m** [comment]
سلام من هم منتظرم... برای دخترم فیلم میریزم توی فلش 
تلویزیون ما هوشمند نیست...
ممنون میشم سریعتر رفع کنید 
چون خیلی نیاز داریم
بچه کوچیک صبر ما بزرگ تر ها رو نداره

**Comment by NabiKAZ** [comment]
<div dir=rtl>

فیلیمو تغییرات زیادی در قالب و سیستم لاگین سایتش داده و متاسفانه من هنوز فرصت نکردم برای اصلاح مشکل، روش وقت بگذارم.
باید به عرضتون برسونم و در جریان باشید که این یک برنامه عام‌المنفعه و متن‌باز است که همه میتونن ایرادات اون رو رفع و توی توسعه اون مشارکت کنند و هیچ نفع مالی برای من نداره و طبیعتاً گارانتی و پشتیبانی تضمین شده ای وجود نداره، به همین دلیل متاسفانه باید عرض کنم که در اولویت آخر کارهای من قرار داره.
ضمن پوزش، انشاله در اولین فرصت روش وقت میگذارم.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

فرصتی دست داد تا بازنگری روی مشکل داشته باشم.
همونطور که گفته بودم بخش لاگین سایت فیلیمو تغییرات عمده ای داشت و تقریباً این بخش از پروژه بازنویسی شد.
لطفاً دوستان تست کنند و اگر مشکلی وجود داشت موضوع جدید باز کنند تا بررسی شود.
ضمناً بخش دونیشن هم اضافه شد اینجا انتهای صفحه توضیح دادم:
https://github.com/NabiKAZ/filimo-downloader#%D8%AD%D9%85%D8%A7%DB%8C%D8%AA
باسپاس
