### ISSUE TITLE
عدم درخواست اطلاعات لاگین

### ISSUE THREAD

**Issue by erfan93** [NabiKAZ/filimo-downloader#27]
اصلا اطلاعات لاگین از من نمیخواد و از این مرحله عبور میکنه و یکراست کد ویدیو رو میخواد همهی مراحل رو 
هم درست میرم

![fil](https://user-images.githubusercontent.com/49561858/56042409-405b4180-5d50-11e9-85d4-2195d5f759b8.PNG)

**Comment by NabiKAZ** [comment]
<div dir=rtl>

ممنون بابت گزارش اشکال. در تیکت 26# میتونید پیگیری کنید.
Duplicate #26
