### ISSUE TITLE
خطا در هنگام درخواست کیفیت فیلم

### ISSUE THREAD

**Issue by alipour66m** [NabiKAZ/filimo-downloader#28]
سلام
در هنگام دانلود فیلم
https://www.filimo.com/m/kwcaj
خطا میدهد
فکر میکنم یک بروز رسانی خوب لازم دارید

**Comment by imani58ir** [comment]
برای سایت فیلمیو میتونین از adds On (firefox) video download helper البته ورژنهای قدیمیش استفاده کنین ...

**Comment by NabiKAZ** [comment]
<div dir=rtl>

احتمال خیلی زیاد این مشکل هم به مشکل لاگین در تیکت #26 مرتبطه.
بله فیلیمو تغییرات اساسی در ساختار سایتش داده که نیاز به بروزرسانی اساسی داریم. انشاله بزودی حل میشه.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

مشکل در همان تیکت #26 حل شد.
