### ISSUE TITLE
روش استفاده در ویندوز

### ISSUE THREAD

**Issue by mohammad021** [NabiKAZ/filimo-downloader#31]
سلام / برای استفاده در ویندوز توضیحی ندادید... یکم ملموس تر بفرمایید...

**Comment by NabiKAZ** [comment]
<div dir=rtl>

در صفحه اول پروژه، نیازمندی ها و برنامه های مورد نیاز و طریقه استفاده کامل نوشته شده. آیا بخش خاصی هست که براتون گنگه یا باهاش مشکل دارید؟

**Comment by mohammad021** [comment]
ازونجا که توضیحی که میبینم در محیط لینوکس هست و نیازه با از putty  استفاده بشه چیزی ندیدم که مربوط به ایجاد تنظیمات برای ویندوز باشه:

> راهنمای استفاده
> ابتدا از طریق این لینک در فیلیمو ثبت نام کنید و حق اشتراک مورد نیاز خود را خریداری نمائید: http://filimo.com/invite/NabiKAZ/a8ca
> 
> از نصب PHP و نسخه‌ی نصب شده بر روی سیستم خود توسط دستور php -v اطمینان حاصل کنید.
> 
> از نصب FFmpeg بر روی سیستم خود توسط دستور ffmpeg اطمینان حاصل کنید.
> 
> سورس برنامه را دانلود کنید.
> 
> در مسیر برنامه و خط فرمان سیستم‌عامل خود دستور زیر را وارد کنید:
> 
> php download.php
> پس از آن یوزر و پسورد از شما خواسته می‌شود و پس از لاگین کد ویدیوی مورد نظر خود که در آدرس بار مرورگر مشاهده می‌کنید را وارد کنید. پس از آن کیفیت‌های در دسترس نشان داده می‌شوند که یکی را انتخاب کنید و دانلود در پس‌زمینه آغاز خواهد شد.

اعمال فوق در ویندوز به نظر نمیاد قابل انجام باشه، یا من درک نکردم...

**Comment by NabiKAZ** [comment]
<div dir=rtl>

برای ویندوز هم بدون تنظیمات اضافه کار میکنه.
بعد از اینکه از نصب برنامه های مورد نیاز مطمئن شدید؛ همون دستورات رو عیناً توی خط فرمان ویندوز (cmd) بنویسید.

**Comment by BabakMehri** [comment]
khob ye film amozeshi chizi bezarid gij shodim bekhoda!

**Comment by NabiKAZ** [comment]
<div dir=rtl>

@BabakMehri 
پیش از هر چیز از توجهتون به پروژه سپاسگزارم.

راه اندازی چندان پیچیده نیست ضمن اینکه هدف اول بحث آموزشی پروژه است و خب جامعه مخاطب بیشتر برنامه نویسان هستند تا کاربران عادی، به همین جهت برای راه اندازی یک سری مقدمات، انتظار میره یک برنامه نویس حداقل اونها رو بدونه.
با این حال راهنمایی های لازم در صفحه اول پروژه شده، اگر درمورد هر کدوم از موارد سوال یا ابهامی داشتید بپرسید بنده درخدمتم.
