### ISSUE TITLE
windows / xampp

### ISSUE THREAD

**Issue by BabakMehri** [NabiKAZ/filimo-downloader#33]
salam man roye windows 10 xampp nasb kardam
FFmpeg ham nasb kardam

download.php ro ejra mikonam in error ro mide

`Filimo Downloader - version 0.1.0 - Copyright 2017-2019 By Nabi KaramAliZadeh Signup here: http://filimo.com/invite/NabiKAZ/a8ca Project link: https://github.com/NabiKAZ/filimo-downloader =========================================================== > Login to filimo.com Input username: 
Warning: Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP) in C:\xampp\htdocs\filimo\download.php on line 41

Warning: fgets() expects parameter 1 to be resource, string given in C:\xampp\htdocs\filimo\download.php on line 41

Fatal error: Uncaught Error: Cannot use object of type stdClass as array in C:\xampp\htdocs\filimo\download.php:51 Stack trace: #0 {main} thrown in C:\xampp\htdocs\filimo\download.php on line 51`

**Comment by NabiKAZ** [comment]
<div dir=rtl>

برنامه تحت وب اجرا نخواهد شد.
برنامه رو تحت خط فرمان اجرا کنید.

در cmd ویندوز وارد بشید و دستور:

php download.php

رو اجرا کنید.
البته قبلش مطمئن بشید php در PATH سیستم ویندوز شما وجود داره و از همه مسیرها قابل دسترسه.
