### ISSUE TITLE
مشکل در دانلود

### ISSUE THREAD

**Issue by elahesharifi** [NabiKAZ/filimo-downloader#34]
<img width="1670" alt="Screen Shot 1398-05-18 at 15 14 12" src="https://user-images.githubusercontent.com/14157953/62773835-75865f00-bab8-11e9-8901-b62b55ad1996.png">
سلام 

   من همه پیشنیازها رو دانلود کردم و لاگین هم کردم ولی برای من اصلن پر نمیشه و برای فیلم‌های دیگه هم امتحان کردم باز شروع به 
دانلود نکرد و فایل سورس برنامه رو هم یه باراز گیتلب استفاده کردم هم یه باراز خود گیتهاب ولی باز در نتیجه فرقی نکرد
ممنون

**Comment by NabiKAZ** [comment]
<div dir=rtl>

لطفاً این مراحل را کنترل کنید:
در ابتدا در خط فرمان، php download.php رو میزنید و یوزر و پسورد و آیدی ویدیو و کیفیت مورد نظر را وارد میکنید.
پیام موفقیت میگیرید و به خط فرمان بر میگردید.
در همین وضعیت task manager را چک کنید و مطمئن شوید که پروسه ffmpeg در پس زمینه در حال کار است.
اکنون دانلود شروع شده، برای دیدن روند پیشرفت، روی وب، به روشی که در راهنمای صفحه اول آمده، از آدرس فایل stats.php (همین عکسی که گذاشتید) روند پیشرفت را باید ببینید.
همچنین اگر به شاخه download مراجعه کنید باید فایل کاور و لاگ مرتبط را آنجا ببینید که دانلود شده.
تا زمانی که گیت هاب بالاست ملاک نسخه گیت هاب است.
لطفاً دوباره تست کنید.

**Comment by elahesharifi** [comment]
ممنون حل شد 
امکانش هست دانلود از فیلم‌نت رو هم فراهم کنید

**Comment by NabiKAZ** [comment]
<div dir=rtl>

خوشحالم که مشکلتون حل شده.
در مورد سرویسهای دیگر هم بله امکان پذیر است، اگر فرصت کنم شاید همه را ادغام و یکپارچه کنم در قالب یک پروژه.
