### ISSUE TITLE
دانلود از Shutterstock.com

### ISSUE THREAD

**Issue by green1112** [NabiKAZ/filimo-downloader#35]
سلام .ممنون از کارهای قشنگ تون.خیلی استفاده کردیم.اگر امکانش باشه برای دانلود از سایت شاتراستوک راهی پیدا کنید بسیار پرطرفدار و کاربردی خواهد بود.

متشکرم.

**Comment by NabiKAZ** [comment]
اون سایت که خودش باید امکان دانلود داشته باشه.
