### ISSUE TITLE
مشکل دانلود

### ISSUE THREAD

**Issue by hamedghafari** [NabiKAZ/filimo-downloader#36]
از کد بسیار کاربردیتون کمال تشکر رو دارم ولی برای بنده با همچین مشکلی روبرو میشه 
تایتل رو آنلاین مینویسه و دیگه ادامه ی کار درست پیش نمیره

![Annotation 2020-01-10 043307](https://user-images.githubusercontent.com/59714352/72117269-57bc6f00-3362-11ea-89b0-555b6859fc79.jpg)

در صورتی که راهنمایی بفرمایید بسیار ممنون میشم .

**Comment by NabiKAZ** [comment]
<div dir=rtl>

سایت هر روز تغییراتی میکنه که هر باره نیاز به اصلاح کدهای روبات است.
اکنون اصلاح شد و لطفاً دوباره تست کنید.

**Comment by medicine88** [comment]
ممنون مشکل حل شد.
