### ISSUE TITLE
مشکل خطای Malformed AAC bitstream detected

### ISSUE THREAD

**Issue by over-soul** [NabiKAZ/filimo-downloader#37]
<span dir='rtl' align='right'>
سلام،

بعد از ورود کد فیلم، یک فایل ویدیو خیلی کوچک دانلود میشه ولی بیشتر از این جلو نمیره. 

ممنون میشم اگر بتوانید کمک کنید. 
</span>

**Comment by NabiKAZ** [comment]
<div dir=rtl>

من تست کردم مشکلی ندیدم.
لطفاً مطمئن بشید که آخرین نسخه رو دانلود و استفاده میکنید.
اگر بدون خطا پیغام bye رو در آخر دیدید یعنی همه چیز درست است و در حال دانلود است و حجم فایل به مرور زیاد میشود و تا تکمیل نشدن دانلود، قابل پخش نیست.

اگر پیغام خطایی دریافت میکنید لطفاً اون رو بگذارید تا بررسی بشه.
اگر هیچ پیغام خطایی ظاهر نمیشود، فایل با پسوند log در شاخه download رو اینجا بگذارید. اگر حجیم بود شاید 10 خط آخر اون هم کفایت کنه.

**Comment by over-soul** [comment]
Log file:
`ffmpeg version 2.8.15-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.10) 20160609
  configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
  libavutil      54. 31.100 / 54. 31.100
  libavcodec     56. 60.100 / 56. 60.100
  libavformat    56. 40.101 / 56. 40.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 40.101 /  5. 40.101
  libavresample   2.  1.  0 /  2.  1.  0
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  2.101 /  1.  2.101
  libpostproc    53.  3.100 / 53.  3.100
[https @ 0x2606380] No trailing CRLF found in HTTP header.
[https @ 0x2a2b420] No trailing CRLF found in HTTP header.
Input #0, hls,applehttp, from 'https://stream7.cdn.asset.filimo.com/filimo-video/157913665830581390/1579194258/060e69641a29ef83b6b4af9f4d0bcc17c3f6d757/26205x264new1-1080p.mp4/chunk.m3u8?wmsAuthSign=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbiI6IjNkMjAwZDYwZmRmM2IwNzQwZmE2OGJmNzA0YjU1MzA5IiwiZXhwIjoxNTc5MTk0MjU4LCJpc3MiOiJTYWJhIElkZWEgR1NJRyJ9.avU-AdQE5CnfVTS9U3AFRf0yGGPn77gemnJaNHMm8iw':
  Duration: 01:35:54.21, start: 0.101000, bitrate: 0 kb/s
  Program 0 
    Metadata:
      variant_bitrate : 0
    Stream #0:0: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p, 1920x914 [SAR 1:1 DAR 960:457], 24 fps, 24 tbr, 90k tbn, 48 tbc
    Stream #0:1: Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 127 kb/s
    Stream #0:2: Data: timed_id3 (ID3  / 0x20334449)
[mp4 @ 0x2ba15e0] Codec for stream 0 does not use global headers but container format requires global headers
[mp4 @ 0x2ba15e0] Codec for stream 1 does not use global headers but container format requires global headers
Output #0, mp4, to 'download/vzAwl_1080p.mp4':
  Metadata:
    encoder         : Lavf56.40.101
    Stream #0:0: Video: h264 ([33][0][0][0] / 0x0021), yuv420p, 1920x914 [SAR 1:1 DAR 960:457], q=2-31, 24 fps, 24 tbr, 90k tbn, 90k tbc
    Stream #0:1: Audio: aac ([64][0][0][0] / 0x0040), 44100 Hz, stereo, 127 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
[mp4 @ 0x2ba15e0] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Operation not permitted
frame=    3 fps=0.0 q=-1.0 Lsize=      20kB time=00:00:00.08 bitrate=1928.5kbits/s    
video:19kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.594087%
Conversion failed!`

**Comment by NabiKAZ** [comment]
<div dir=rtl>

در این خط از کد:

<div dir=ltr>

https://github.com/NabiKAZ/filimo-downloader/blob/8ceecb82e3a618eb6a81648b159c1aae37575674/download.php#L201
<div dir=rtl>

تبدیل به این کنید:

<div dir=ltr>

```
$cmd = 'ffmpeg ' . $cmd_proxy . ' -i "' . $qualities[$input]['url'] . '" -c:v copy -c:a copy -bsf:a aac_adtstoasc -y "' . $video_file . '"';
```
<div dir=rtl>
سپس لطفاً دوباره تست کنید و نتیجه رو اینجا بنویسید.

**Comment by over-soul** [comment]
درست شد. خیلی ممنون

**Comment by NabiKAZ** [comment]
<div dir=rtl>

آپدیت شد.
