### ISSUE TITLE
💵 دونیشن‌های شما همراه با ❤️

### ISSUE THREAD

**Issue by NabiKAZ** [NabiKAZ/filimo-downloader#38]
<div dir=rtl>

دوستان خوبم!
لطفاً اگر دونیشنی انجام دادید، اینجا پیام بگذارید تا براتون ❤️ بفرستم 😉

پرداخت آنلاین:
https://zarinp.al/nabikaz
_(لطفاً حتماً در توضیحات آن، نام این پروژه را ذکر کنید)_

**Comment by mahdimf1** [comment]
با سلام من این پروژه رو رو لینوکس نتونستم ران کنم. فکر کنم نسخه جدید تری باید ارایه کنید ممنون می شم راهنمایی کنید

**Comment by NabiKAZ** [comment]
@mahdimf1
<div dir=rtl>
لطفاً تیکت جدید با موضوع مناسب باز کنید و نیز توضیحات فنی کافی ارائه دهید.
