### ISSUE TITLE
مشکل در دانلود

### ISSUE THREAD

**Issue by mrmilgh** [NabiKAZ/filimo-downloader#40]
سلام و خسته نباشید بابت زحماتتون
متاسفانه این اسکریپت از کار افتاده و فقط یکی دو دقیقه ی اول فیلما رو دانلود میکنه و همونجا میمونه و ادامشو نمیگیره
امکانش هست یه بررسی بفرمایید؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>
پوزش از اینکه با تاخیر پاسخ میدم.

من الان در این تاریخ تست کردم مشکلی ندیدم، با توجه به اینکه زمان زیادی از موضوع تیکت گذشته، لطفاً دوباره تست کنید و چنانچه مشکل باقی بود با ذکر جزئیات فنی بیشتر تیکت را باز کنید تا بررسی شود.

در ضمن اگر اشتباه نکنم چند وقت پیش جایی دیدم فیلیمو نوشته بود یه مدت کوتاهی از همه فیلمها رو بدون تهیه اشتراک میشه تماشا کرد، مطمئن بشید مشکل شما به این موضوع مربوط نبوده است.
