### ISSUE TITLE
Movies with two audio languages download without sound

### ISSUE THREAD

**Issue by over-soul** [NabiKAZ/filimo-downloader#41]
Hello, 

Movies that are dubbed (have English and Farsi audio) download without any sound. Is there any way to fix this?

Thanks!

**Comment by SaeedDev94** [comment]
Hi, You can try my FilimoPlus WebApp:
https://github.com/Saeed-Pooyanfar/filimo-plus
I just added support for movies with 2 audio sources!

**Comment by NabiKAZ** [comment]
I checked several dubbed movies but did not find any that had two voices. Can you introduce a sample video for review?

**Comment by alibroujerdi** [comment]
This one has two audio source and after download it has no sound
5PbD6

**Comment by NabiKAZ** [comment]
<div dir=rtl>

این ویژگی پیاده سازی شد.

در صورتی که صورت های مختلف پیدا شود، گزینه مورد نظر دریافت میشود:
<div dir=ltr>

```
Select Audio:
1) LANGUAGE = en
2) LANGUAGE = fa
Input option number:
```
<div dir=rtl>

و سپس صورت انتخابی با ویدیو به شکل خودکار ادغام میشود.
