### ISSUE TITLE
Undefined variable: video_url on line 166 

### ISSUE THREAD

**Issue by pakatchian** [NabiKAZ/filimo-downloader#42]
باسلام
در روزهای اخیر با ورود شناسه ویدئو پیغام خطا ظاهر میشه 
Notice: Undefined variable: video_url on line 166 
Error: Can not fetch video URL

**Comment by mohammad-ghorbani** [comment]
این پیغام فقط برای فایلهای جدید که از دیروز بروزرسانی شده اند میاید، قبلی ها مشکلی نداره

**Comment by northvector** [comment]
منم با این مشکل مواجه شدم ولی روش حل کردنش اسونه کافیه سورس صفحه پلیر رو بیاری 

var player_data = {"multiSRC":[[{"src":"https:\/\/www.filimo.com\/movie\/watch\/m3u8\/mof\/yes\/v\/1\/usid\/49575334\/uid\/159623234991260724\/tot\/1596117149\/utp\/785462790\/movie_uid\/HOXMu\/movie_id\/37538\/devicetype\/site\/agentsdk\/0\/agentafcn\/159596051818818\/smart\/0\/hash_url\/928283cf7673142320e07bc8242bd5c8\/hash_urln\/21337c09f6fbc45453bb28740ba09c3a\/afcn\/159596051818818\/movie.m3u8","type":"application\/vnd.apple.mpegurl"}]]

یه همچین قسمتی پیدا کنی و src رو برداری
بعد فایل download.php رو ادیت بزنی که از همین ادرس بگیره
تموم

**Comment by northvector** [comment]
بعد یه سوال دارم امکان اجرای این script روی سرور هم هست؟ برای ساخت ربات تلگرام

**Comment by mohammad-ghorbani** [comment]
اینی که شما گفتی برای یک قسمت اون سریال جوابه ولی چیزهای دیگه رو که نه

**Comment by arashrahimi46** [comment]
یه پول رکویست دادم برای این قضیه اگر اکسپت بشه و مرج بشه  مشکلشو درست کردم

**Comment by NabiKAZ** [comment]
> این پیغام فقط برای فایلهای جدید که از دیروز بروزرسانی شده اند میاید، قبلی ها مشکلی نداره

<div dir=rtl>
پوزش از اینکه با تاخیر پاسخ میدم.

من الان در این تاریخ تست کردم مشکلی ندیدم، با توجه به اینکه زمان زیادی از موضوع تیکت گذشته، لطفاً دوباره تست کنید و چنانچه مشکل باقی بود با ذکر جزئیات فنی بیشتر تیکت را باز کنید تا بررسی شود.
و بفرمائید برای کدام ویدیو مشکل وجود داشته است؟

**Comment by NabiKAZ** [comment]
> بعد یه سوال دارم امکان اجرای این script روی سرور هم هست؟ برای ساخت ربات تلگرام

<div dir=rtl>
بله پروژه متن باز و تحت لایسنس GPL-3 ارائه شده است و در صورت رعایت مفاد لایسنس، میتوانید آن را به هر شکل توسعه دهید.

**Comment by NabiKAZ** [comment]
<div dir=rtl>
با توجه به گذشت زمان و اینکه بنده تست کردم مشکلی ندیدم، تیکت را میبندم، اگر مشکل باقی بود مجدداً آن را باز کنید تا بررسی شود.
