### ISSUE TITLE
curl_init

### ISSUE THREAD

**Issue by pooyahesabi** [NabiKAZ/filimo-downloader#45]
man barnameye Filimo downloader ro nasb kardam vali in error ro mide:
Fekr mikonam systeme login eshtebah hast
__________________________________________________________________________________________________________
C:\Program Files\php-7.4.13\filimo>php download.php
Filimo Downloader - version 0.1.0 - Copyright 2017-2019
By Nabi KaramAliZadeh <www.nabi.ir> <nabikaz@gmail.com>
Signup here: http://filimo.com/invite/NabiKAZ/a8ca
Project link: https://github.com/NabiKAZ/filimo-downloader
===========================================================

Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Program Files\php-7.4.13\filimo\download.php:247
Stack trace:
#0 C:\Program Files\php-7.4.13\filimo\download.php(16): get_contents('https://www.fil...')
#1 {main}
  thrown in C:\Program Files\php-7.4.13\filimo\download.php on line 247

**Comment by NabiKAZ** [comment]
see: https://github.com/NabiKAZ/namava-downloader/issues/63

**Comment by NabiKAZ** [comment]
Duplicate #16
