### ISSUE TITLE
پیدا نشدن $video_url هنگام دانلود به دلیل کارکتر ; در رشته دیتا

### ISSUE THREAD

**Issue by esi1235618** [NabiKAZ/filimo-downloader#46]
سلام و درود. 
بابت این نرم افزاری که درست کردید ممنون
یک مشکلی که هستش اینه که موقعی که می خوام فیلم با حجم بالا رو دانلود کنم خطا می ده. برای مثال سریال های کوتاه رو به درستی دانلود می کنه ولی می خوام یک فیلم با حجم بالا و مدت زمان بالا دانلود کنم خطا می ده. 

PHP Warning:  foreach() argument must be of type array|object, null given in C:\Users\AmirAli\Desktop\1\download.php on line 159

Warning: foreach() argument must be of type array|object, null given in C:\Users\AmirAli\Desktop\1\download.php on line 159
PHP Warning:  Undefined variable $video_url in C:\Users\AmirAli\Desktop\1\download.php on line 166

Warning: Undefined variable $video_url in C:\Users\AmirAli\Desktop\1\download.php on line 166
Error: Can not fetch video URL.

این خطا رو می ده. چند تا فیلم رو تست کردم انجام ندادش ولی انیمیشن های کوچیک رو به راحتی دانلود می کنه
ممنون می شم جواب بدید

**Comment by NabiKAZ** [comment]
<div dir=rtl>

میتونید آیدی یکی از ویدیوهایی که اشکال داره رو بگید تا تست کنم؟

**Comment by alibroujerdi** [comment]
این چند تا آی دی همین خطا رو میدن
BkjGr
xkvm7
uk3CO

**Comment by NabiKAZ** [comment]
<div dir=rtl>

ظاهراً وجود کارکتر `;` شبیه این:
`},"director":"Liam O&#039;Donnell",`
در دیتای برخی فیلمها باعث بروز این اشکال شده بود.

مشکل اکنون حل شد و پس از دانلود آخرین نسخه، مجدد امتحان کنید.

ممنون بابت گزارش این اشکال.
