### ISSUE TITLE
خطا به هنگام ورود دستورphp download.php 

### ISSUE THREAD

**Issue by vahid-merikhy** [NabiKAZ/filimo-downloader#47]
خسته نباشید 
هنگام وارد کردن دستور 

php download.php
خطای پیین رو میده

PS C:\Users\Administrator\Desktop\filimo-downloader-master> php download.php
Filimo Downloader - version 0.1.0 - Copyright 2017-2019
By Nabi KaramAliZadeh <www.nabi.ir> <nabikaz@gmail.com>
Signup here: http://filimo.com/invite/NabiKAZ/a8ca
Project link: https://github.com/NabiKAZ/filimo-downloader
===========================================================
PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in C:\Users\Administrator\Desktop\filimo-downloader-master\download.php:261
Stack trace:
#0 C:\Users\Administrator\Desktop\filimo-downloader-master\download.php(16): get_contents('https://www.fil...')
#1 {main}
  thrown in C:\Users\Administrator\Desktop\filimo-downloader-master\download.php on line 261

Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\Administrator\Desktop\filimo-downloader-master\download.php:261
Stack trace:
#0 C:\Users\Administrator\Desktop\filimo-downloader-master\download.php(16): get_contents('https://www.fil...')
#1 {main}
  thrown in C:\Users\Administrator\Desktop\filimo-downloader-master\download.php on line 261
PS C:\Users\Administrator\Desktop\filimo-downloader-master>

**Comment by Parxa1** [comment]
سلام کد فیلم رو که میزنم این خطا رو میاره 
Warning: Undefined array key 1 in /data/data/com.termux/files/home/filimo-downloader/download.php on line 139
Duration:  min

Warning: Undefined array key 1 in /data/data/com.termux/files/home/filimo-downloader/download.php on line 147
===========================================================

Warning: foreach() argument must be of type array|object, null given in /data/data/com.termux/files/home/filimo-downloader/download.php on line 159

Warning: Undefined variable $video_url in /data/data/com.termux/files/home/filimo-downloader/download.php on line 166
Error: Can not fetch video URL.

**Comment by NabiKAZ** [comment]
> خسته نباشید
> هنگام وارد کردن دستور
> 
> php download.php
> خطای پیین رو میده
> 
> # PS C:\Users\Administrator\Desktop\filimo-downloader-master> php download.php
> Filimo Downloader - version 0.1.0 - Copyright 2017-2019
> By Nabi KaramAliZadeh <www.nabi.ir> [nabikaz@gmail.com](mailto:nabikaz@gmail.com)
> Signup here: http://filimo.com/invite/NabiKAZ/a8ca
> Project link: https://github.com/NabiKAZ/filimo-downloader
> PHP Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\Administrator\Desktop\filimo-downloader-master\download.php:261
> Stack trace:
> #0 C:\Users\Administrator\Desktop\filimo-downloader-master\download.php(16): get_contents('https://www.fil...')
> #1 {main}
> thrown in C:\Users\Administrator\Desktop\filimo-downloader-master\download.php on line 261
> 
> Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\Administrator\Desktop\filimo-downloader-master\download.php:261
> Stack trace:
> #0 C:\Users\Administrator\Desktop\filimo-downloader-master\download.php(16): get_contents('https://www.fil...')
> #1 {main}
> thrown in C:\Users\Administrator\Desktop\filimo-downloader-master\download.php on line 261
> PS C:\Users\Administrator\Desktop\filimo-downloader-master>

see: https://github.com/NabiKAZ/namava-downloader/issues/63

**Comment by NabiKAZ** [comment]
> سلام کد فیلم رو که میزنم این خطا رو میاره
> Warning: Undefined array key 1 in /data/data/com.termux/files/home/filimo-downloader/download.php on line 139
> Duration: min
> 
> # Warning: Undefined array key 1 in /data/data/com.termux/files/home/filimo-downloader/download.php on line 147
> Warning: foreach() argument must be of type array|object, null given in /data/data/com.termux/files/home/filimo-downloader/download.php on line 159
> 
> Warning: Undefined variable $video_url in /data/data/com.termux/files/home/filimo-downloader/download.php on line 166
> Error: Can not fetch video URL.

<div dir=rtl>

خطای شما ارتباطی به موضوع تیکت و خطایی که دوستمون گذاشتند نداشت. برای موضوعات جدید لطفاً تیکت جدید باز کنید.
در هر صورت آپدیت کنید و چنانچه مشکل باقی بود، با ذکر شماره ویدیوی و نسخه PHP خود، در تیکت جدیدی موضوع را طرح کنید.
