### ISSUE TITLE
Error: Expire auth token.

### ISSUE THREAD

**Issue by Iman-Mehregan-zz** [NabiKAZ/filimo-downloader#48]
با سلام و احترام
لطفا راهنمايي بفرماييد كه زمانيكه كوكي اكسپاير ميشه چطور ميتونيم مشكل را حل كنيم و مجددا لاگين كنيم؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

عرض ارادت،
نیاز به کار خاصی نیست، شما زمانی که کد رو اجرا میکنید، اول چک میکنه کوکی قبلی معتبر هست یا نه و اگر نبود و لاگین نبودید، ازتون یوزر و پسورد میگیره و کوکی جدید رو جایگزین قبلی میکنه. با این حال اگر میخواستید یکبار مجدد لاگین بشید، میتونید دستی فایل config\cookies.txt رو حذف کنید.

**Comment by Iman-Mehregan-zz** [comment]
الان مدتي است كه امكان لاگين وجود نداره و پيغام 
Expire auth token.
صادر ميشه و برنامه ديگه يوزر نيم و پسورد را نميپرسه
به نظر ميرسه مشكل بوجود آمده ناشي از تغييرات دوباره صفحه لاگين فيليمو باشه
ممنون ميشم بررسي بفرماييد
با سپاس فراوان

**Comment by NabiKAZ** [comment]
<div dir=rtl>

ممنون از اینکه باگ رو گزارش دادید.
مشکل اکنون حل شد و میتونید آپدیت کنید.
