### ISSUE TITLE
Error: Expire auth token.

### ISSUE THREAD

**Issue by hamedghafari** [NabiKAZ/filimo-downloader#49]
سلام و عرض خسته نباشید 
اسکریپت دانلود از کار افتاده کاملا و موقع اجرای برنامه ارور بالا ظاهر میشه و دیگه یوزر و پسوورد نمیخواد که لاگین بشه 
لطف کنید یه بررسی بفرمایید .

**Comment by NabiKAZ** [comment]
Duplicate https://github.com/NabiKAZ/filimo-downloader/issues/48
