### ISSUE TITLE
farsi in xaamp

### ISSUE THREAD

**Issue by Iman-Mehregan-zz** [NabiKAZ/filimo-downloader#50]
با سلام عرض ادب و احترام
ممنونم ، مشكل دانلود حل شد
يك سوال از حضورتون دارم
من از ترمينال xampp 
در ويندوز 10 براي اجراي برنامه استفاده ميكنم ولي موقع دريافت پيام فارسي، فونت ها در محيط
 shell xaampp  
به هم ريخته است.
آيا راهي وجود داره كه پيام هاي دريافتي از سمت سرور را بشه بصورت فارسي و صحيح ديد؟
ممنون از برنامه خوبتون و وقتي كه مي گذاريد

**Comment by NabiKAZ** [comment]
<div dir=rtl>

ممنون از محبت شما.

چند راه حل اینجا مطرح شده:
https://github.com/NabiKAZ/namava-downloader/issues/11
