### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Legend1987** [NabiKAZ/filimo-downloader#51]
C:\Users\Administrator\Downloads\Compressed\filimo-downloader-master\filimo-downloader-master>php download.php
Filimo Downloader - version 0.1.0 - Copyright 2017-2019
By Nabi KaramAliZadeh <www.nabi.ir> <nabikaz@gmail.com>
Signup here: http://filimo.com/invite/NabiKAZ/a8ca
Project link: https://github.com/NabiKAZ/filimo-downloader
===========================================================

Fatal error: Uncaught Error: Call to undefined function curl_init() in C:\Users\Administrator\Downloads\Compress
ed\filimo-downloader-master\filimo-downloader-master\download.php:261
Stack trace:
#0 C:\Users\Administrator\Downloads\Compressed\filimo-downloader-master\filimo-downloader-master\download.php(16
): get_contents('https://www.fil...')
#1 {main}
  thrown in C:\Users\Administrator\Downloads\Compressed\filimo-downloader-master\filimo-downloader-master\downlo
ad.php on line 261

C:\Users\Administrator\Downloads\Compressed\filimo-downloader-master\filimo-downloader-master>

**Comment by Legend1987** [comment]
Fix it

**Comment by NabiKAZ** [comment]
https://github.com/NabiKAZ/namava-downloader/issues/63
