### ISSUE TITLE
از کار افتادن اسکریپت

### ISSUE THREAD

**Issue by mrmilgh** [NabiKAZ/filimo-downloader#52]
سلام
متاسفانه چند روزیه اسکریپت از کار افتاده و نمیتونه لینک دانلود ویدیو رو پیدا کنه و خطای زیر رو میده :
`PHP Warning:  foreach() argument must be of type array|object, null given in C:\Users\Administrator\Downloads\Compressed\filimo-downloader-master\download.php on line 159
PHP Warning:  Undefined variable $video_url in C:\Users\Administrator\Downloads\Compressed\filimo-downloader-master\download.php on line 166
Error: Can not fetch video URL.`

**Comment by NabiKAZ** [comment]
من الان تست کردم مشکلی ندیدم، لینک ویدیویی که باش مشکل دارید رو لطفاً بفرمائید.

**Comment by mrmilgh** [comment]
با تمام ویدیوها مشکل دارم کلا هیچی دانلود نمیشه از فیلیمو، ارور بالا رو میده و نمیتونه لینک ویدئو رو پیدا کنه، تا یکی دوماه پیش مشکلی نداشت

**Comment by NabiKAZ** [comment]
برای نمونه میتونید آیدی یک ویدیو رو که وارد میکنید رو لطفاً بگید؟

**Comment by mrmilgh** [comment]
خدمت شما : pe5y8

**Comment by NabiKAZ** [comment]
من هیچ مشکلی مشاهده نکردم:
![image](https://user-images.githubusercontent.com/246721/147325304-a2b9bc77-c6d8-49ef-a637-7bb30377c9f5.png)
لطفاً خروجی این دستورات رو بفرمائید:
php -v
php -m
ffmpeg -version
