### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by mazyshm** [NabiKAZ/filimo-downloader#53]
سلام 

وقتی که  php download.php رو اجرا میکنم این ارور رو میگیرم ممنون میشم اگه کمک کنید.

![Error](https://user-images.githubusercontent.com/54486369/153681066-f9e35649-b21c-4a76-970c-b0259cf987e8.png)
![php version](https://user-images.githubusercontent.com/54486369/153681056-065c58d7-e2ad-4406-9c84-fd5097e6c5cb.png)

.

**Comment by NabiKAZ** [comment]
see: https://github.com/NabiKAZ/namava-downloader/issues/63
Duplicate #16
