### ISSUE TITLE
خطای Call to undefined function curl_init() 

### ISSUE THREAD

**Issue by imanmoo** [NabiKAZ/filimo-downloader#54]
درود و خسته نباشید. دوست عزیز واسه ی رفع این خطا باید چیکار کرد؟ ممنون میشم بهم کمک کنید. مرسی
![Capture1](https://user-images.githubusercontent.com/17161843/155357632-80c43ec1-4b58-41f8-9d72-c072d08f2548.PNG)

**Comment by NabiKAZ** [comment]
Duplicate https://github.com/NabiKAZ/filimo-downloader/issues/55
