### ISSUE TITLE
Error: Expire auth token.

### ISSUE THREAD

**Issue by medicine88** [NabiKAZ/filimo-downloader#57]
سلام.برا لاگین شدن ارور Error: Expire auth token.
ممنون میشم بررسی کنین.

**Comment by NabiKAZ** [comment]
لاگین تست شد. مشکلی مشاهده نشد.
مطمئن بشید آخرین نسخه رو گرفتید.
یکبار config/cookies.txt رو حذف کنید و دوباره تست کنید.
با شماره لاگین کنید، نباید مشکلی باشد.

**Comment by medicine88** [comment]
ممنون.مشکل حل شد.فقط آخرین ورژن رو جایگزین کنین.
