### ISSUE TITLE
فیلم نت

### ISSUE THREAD

**Issue by majid1919** [NabiKAZ/filimo-downloader#60]
سلام خسته نباشید 

امکانش هست همین کد رو برای فیلم نت منتشر کنید 
سپاس

**Comment by NabiKAZ** [comment]
به لحاظ فنی که امکانش هست. اما کو وقت آزاد و انگیزه! (:

**Comment by majid1919** [comment]
> به لحاظ فنی که امکانش هست. اما کو وقت آزاد و انگیزه! (:
آره واقعا
همون وقتی که واسه کد نماوا و فیلیمو گذاشتید شایان تقدیر هستش
سپاس
