### ISSUE TITLE
مشکل لاگین کردن

### ISSUE THREAD

**Issue by hamidbn** [NabiKAZ/filimo-downloader#7]
با تشکر از برنامه خوبتون 
راستش موقع ورود همش ارور میده با اینکه یوزر و پسورد رو درست وارد میکنم
در ضمن میدونید که پسورد خاصی وجود نداره و هر بار پسورد پیامک میشه برای ادم

**Comment by NabiKAZ** [comment]
<div dir=rtl>
شما نباید از روش ورود توسط پسورد پیامکی استفاده کنید.
اگر یوزر و پسورد ثابت ندارید، یکبار در aparat.com با همون شماره ای که در فیلیمو عضو هستید، عضو بشید، سپس با همون یوزر و پسوردتون میتونید در فیلیمو هم لاگین بشید. برای استفاده از این برنامه هم از همین یوزر و پسورد استفاده کنید.
