### ISSUE TITLE
امکان دانلود زیرنویس

### ISSUE THREAD

**Issue by hamidbn** [NabiKAZ/filimo-downloader#8]
چرا امکان دانلود زیرنویس ها رو ندارد ؟

**Comment by NabiKAZ** [comment]
<div dir=rtl>

چراش که خب به خاطر اینه که چنین ویژگی در کد پیشبینی و اجرا نشده بود.😉    

اما بنا به پیشنهاد شما، این قطعه کد اکنون اضافه شد.

اکنون در صورت داشتن زیرنویس، به صورت خودکار تشخیص و با پسوند `srt` دانلود میشود.

تنها نکته اینکه، در مورد برخی پلیرها که امکان پخش این فایل را ندارند، کافیست آن را ویرایش و کلمه `WEBVTT` را از ابتدای آن حذف کنید.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

دیگه `WEBVTT` هم خودکار حذف میشه. #9

**Comment by bugatti2018** [comment]
برای بهترین زیرنویس های فارسی فقط به سایت ایران زیرنویس مراجع کنید ، ایران زیرنویس مرجع [دانلود زیرنویس فارسی](http://iranzirnevis.com/) فیلم، سریال و انیمیشن

**Comment by NabiKAZ** [comment]
<div dir=rtl>
@bugatti2018 الان چه ربطی داشت؟ اینجا جای تبلیغ نیست دوست من!

**Comment by alishjackson** [comment]
# [برای دانلود زیرنویس وارد سایت زیربشوید:](http://findstitle.ir)

# [http://findstitle.ir](http://findstitle.ir)

# [مرجع دانلود میلیون ها زیرنویس برای تمام زبان ها:](http://findstitle.ir)
کلیک کنید
































































/





















































.





























































.

























































.












































.

**Comment by NabiKAZ** [comment]
<div dir=rtl>

@alishjackson تبلیغ اینقدر تابلو و زننده گلم؟ ;-)
